Algoritmo "escolha caso exercicio"
Var
UF: caracter


Inicio
escreva("UF do estado?: ")
leia(UF)

escolha UF
        caso "SC"
        escreva("Santa Catarina")
        caso "SP"
        escreva("São Paulo")
        caso "RR"
        escreva("Roraima")
        caso "AM"
        escreva("Amazônia")
        outrocaso
        escreva("Estado desconhecido")
fimescolha


Fimalgoritmo